SELECT
  COUNT(*) OVER() AS TOTAL,
  PS.VENDOR_ID,
  HP.PARTY_NAME AS NOME_FORNECEDOR,
  HP.PARTY_NUMBER AS PARTE,
  PS.SEGMENT1 AS CODIGO_FORNECEDOR,
  PS.VENDOR_TYPE_LOOKUP_CODE AS TIPO_FORNECEDOR,
  PS.TAXPAYER_COUNTRY AS PAIS_FISCAL,
  PS.CREATION_SOURCE AS TIPO_CRIACAO,
  PS.CREATED_BY AS CRIADO_POR,
  TO_CHAR(
    FROM_TZ(CAST(PS.CREATION_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS DATA_CRIACAO,
  PS.LAST_UPDATED_BY,
  TO_CHAR(
    FROM_TZ(CAST(PS.LAST_UPDATE_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS DATA_ATUALIZACAO
FROM
  POZ_SUPPLIERS PS
  LEFT JOIN HZ_PARTIES HP ON PS.PARTY_ID = HP.PARTY_ID
WHERE
  1 = 1
  /*TRUNC(
          FROM_TZ(CAST(PS.LAST_UPDATE_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO'
        )
        BETWEEN TO_DATE('11/11/2025', 'DD/MM/YYYY')
            AND TO_DATE('11/11/2025', 'DD/MM/YYYY')
      */
  AND TRUNC(
    FROM_TZ(CAST(PS.CREATION_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO'
  ) BETWEEN TO_DATE('01/11/2025', 'DD/MM/YYYY')
  AND TO_DATE('30/11/2025', 'DD/MM/YYYY') --  AND PS.CREATED_BY = 'LEONARDO.GUILHERME@NINECON.COM.BR'
ORDER BY
  PS.CREATION_DATE DESC

