select
  ieba.account_classification,
  ieba.bank_account_name,
  ieba.bank_account_name_alt,
  ieba.bank_account_num,
  ieba.bank_account_num_electronic,
  -- ieba.bank_account_num_hash1,
  -- ieba.bank_account_num_hash2,
  ieba.bank_account_type,
  -- ieba.bank_acct_verif_status_code,
  -- ieba.bank_branch_name,  
  -- ieba.bank_branch_party_flag,
  ieba.bank_id,
  -- ieba.bank_name,
  -- ieba.bank_number,  
  -- ieba.ba_num_elec_sec_segment_id,
  -- ieba.ba_num_sec_segment_id,  
  ieba.branch_id,
  ieba.branch_number,
  ieba.check_digits,
  ieba.country_code,
  ieba.description,
  -- ieba.eft_swift_code,
  -- ieba.encrypted,
  -- ieba.enterprise_id,
  -- ieba.exchange_rate,
  -- ieba.exchange_rate_agreement_num,  
  -- ieba.exchange_rate_agreement_type,
  ieba.ext_bank_account_id,
  ieba.foreign_payment_use_flag,
  -- ieba.hedging_contract_reference,
  ieba.iban,
  -- ieba.iban_hash1,
  -- ieba.iban_hash2,
  -- ieba.iban_sec_segment_id,
  -- ieba.job_definition_name,
  -- ieba.job_definition_package,
  -- ieba.last_change_hist_id,  
  -- ieba.last_update_login,
  ieba.masked_iban,
  -- ieba.object_version_number,
  -- ieba.origin_application_id,
  -- ieba.orig_system,
  -- ieba.orig_system_reference,
  -- ieba.payment_factor_flag,
  -- ieba.program_application_id,
  -- ieba.program_id,
  -- ieba.program_update_date,
  -- ieba.request_id,
  -- ieba.salt_version,
  -- ieba.secondary_account_reference,
  to_char(from_tz(cast(ieba.start_date as timestamp), 'utc') at time zone 'america/sao_paulo', 'dd/mm/yyyy hh24:mi:ss') as data_inicio,
  to_char(from_tz(cast(ieba.end_date as timestamp), 'utc') at time zone 'america/sao_paulo', 'dd/mm/yyyy hh24:mi:ss') as data_fim,  
  -- ieba.vat_bank_account_id,
  ieba.created_by,
  to_char(from_tz(cast(ieba.creation_date as timestamp), 'utc') at time zone 'america/sao_paulo', 'dd/mm/yyyy hh24:mi:ss') as criado_em,
  ieba.last_updated_by,
  to_char(from_tz(cast(ieba.last_update_date as timestamp), 'utc') at time zone 'america/sao_paulo', 'dd/mm/yyyy hh24:mi:ss') as atualizado_em    
from 
  iby_ext_bank_accounts ieba
where
  1 = 1
order by 
  ieba.start_date desc
