SELECT
  auce.REQUEST_ID,
  auce.CUST_ERROR_ID,
  auce.BATCH_ID,
  auce.ORIG_SOURCE_SYSTEM,
  auce.PARTY_ORIG_SYSTEM_REFERENCE,
  auce.SITE_ORIG_SYSTEM_REFERENCE,
  auce.LOCATION_ORIG_SYSTEM_REFERENCE,
  auce.CUST_ORIG_SYSTEM_REFERENCE,
  auce.CUST_SITE_ORIG_SYS_REF,
  auce.CUST_SITEUSE_ORIG_SYS_REF,
  auce.INTERFACE_TABLE_NAME,
  auce.ERROR_MESSAGE_NAME,
  auce.ORIGINAL_ERROR_MESSAGE,
  auce.CREATED_BY,
  TO_CHAR(
    FROM_TZ(CAST(auce.creation_date AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Sao_Paulo',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS DATA_CRIACAO,
  auce.LAST_UPDATED_BY,
  TO_CHAR(
    FROM_TZ(CAST(auce.last_update_date AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Sao_Paulo',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS LAST_UPDATE_DATE
FROM
  AR_UPD_CUST_ERRORS auce
WHERE
  TRUNC(
    FROM_TZ(CAST(auce.last_update_date AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Sao_Paulo'
  ) = TO_DATE('05/11/2025', 'DD/MM/YYYY')    
ORDER BY
  auce.last_update_date DESC
