-- BUSCA OS ERROS DE IMPORTACAO DA TABELA DE FORNECEDOR
SELECT
  COUNT(*) OVER() AS TOTAL,
  PSIR.REJECTION_ID,
  PSIR.PARENT_TABLE,
  PSIR.PARENT_ID,
  PSIR.VALUE,
  PSIR.REJECT_LOOKUP_CODE,
  PSIR.APP_NAME,
  PSIR.ATTRIBUTE,
  --  PSIR.OBJECT_VERSION_NUMBER,
  --  PSIR.REQUEST_ID,
  --  PSIR.JOB_DEFINITION_NAME,
  --  PSIR.JOB_DEFINITION_PACKAGE,
  PSIR.LAST_UPDATED_BY,
  TO_CHAR(
    FROM_TZ(CAST(PSIR.LAST_UPDATE_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS LAST_UPDATE_DATE,
  --  PSIR.LAST_UPDATE_LOGIN,
  PSIR.CREATED_BY,
  TO_CHAR(
    FROM_TZ(CAST(PSIR.CREATION_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO',
    'DD/MM/YYYY HH24:MI:SS'
  ) AS CREATION_DATE
FROM
  POZ_SUPPLIER_INT_REJECTIONS PSIR
WHERE
  1 = 1
  AND TRUNC(
    FROM_TZ(CAST(PSIR.CREATION_DATE AS TIMESTAMP), 'UTC') AT TIME ZONE 'AMERICA/SAO_PAULO'
  ) BETWEEN TO_DATE('01/11/2025', 'DD/MM/YYYY')
  AND TO_DATE('30/11/2025', 'DD/MM/YYYY')
ORDER BY
  PSIR.CREATION_DATE DESC
